story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('story-1/', include('story_1.urls')),

    # path('story-x/', include('story_x.urls')), do this for each new story, and update the landing page with the latest story

    path('error/', include('error_handler.urls')),
    path('profile/', include('story_1.urls')),
    path('', include('story_3.urls')),
    path('schedule/', include('story_5.urls')),
    path('activity/', include('story_6.urls')),
    path('flexes/', include('story_7.urls')),
    path('books/', include('story_8.urls')),
    path('game/', include('story_9.urls')),
    path('copypasta/', include('copypasta.urls')),
]

handler400 = 'error_handler.views.error_400'
handler403 = 'error_handler.views.error_403'
handler404 = 'error_handler.views.error_404'
handler500 = 'error_handler.views.error_500'

story_9/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'story_9'

urlpatterns = [
    path('', views.index, name='index'),
    path('id/<str:username>/', views.profile, name='profile'),
    path('login/', views.loginview, name='login'),
    path('loginapi/', views.loginapi, name='loginapi'),
    path('signupapi/', views.signupapi, name='signupapi'),
    # path('login/', auth_views.LoginView.as_view(template_name="login_django.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout_django.html"), name='logout'),
    path('signup/', views.signupview, name='signup'),
    path('claim/', views.claim, name='claim'),
]

story_9/models.py
import json

from django.db import models

# Importing the user model django provided
from django.contrib.auth.models import User;

# Hello Hocky please read this in the future if you need help

# In many cases when there is a modification in a model’s instance we need execute some action. Django provides us an elegant way to handle these situations. The signals are utilities that allow us to associate events with actions. We can develop a function that will run when a signal calls it.

# Reference of usage:
# - https://medium.com/@ksarthak4ever/django-signals-b20a4152a27b
# - https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length = 128, default = "", blank = True)
    photo = models.URLField(default = "https://i.pinimg.com/originals/b6/57/c3/b657c3b864b96fe5eefc60bd8841cda4.gif")
    score = models.IntegerField(default=500)
    last_claimed = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.user.__str__()

@receiver(post_save, sender=User)
def save_profile(sender, instance, created, **kwargs):
    if(created):
        Profile.objects.create(user=instance)
    instance.profile.save()
    

story_9/forms.py
from django.forms import ModelForm, DateTimeInput, CheckboxInput
from .models import *

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user', 'score']
        labels = {
            'full_name': '',
            'photo': ''
        }
        # widgets = {
        #     'semester_parity': CheckboxInput(attrs={'data-toggle': 'toggle', 'data-on': "Odd", "data-off": "Even", 'data-onstyle':'primary', 'data-offstyle':'warning'})
        # }

story_9/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User, Profile
from .forms import ProfileForm
from random import randint
import copy

# Reference:
# https://docs.djangoproject.com/en/3.1/topics/auth/default/#django.contrib.auth.views.LoginView
# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://github.com/django/django/blob/master/django/contrib/auth/forms.py

original = {
    "description" : "Hocky Yudhiono's personal website",
    "title" : "Hey! It's Hocky!",
    "showfooter" : True,
    "stickynav" : True,
    "ismain" : False,
}

def index(request):
    # print(request.session)
    # print(request)
    # print(type(request))
    # try:
    #     print(request.user)
    #     print(type(request.user))
    # except:
    #     print("Not available")
    context = copy.copy(original)
    context["description"] = f"I've won.. But at what cost"
    context["title"] = f"Compete?"
    leaderboard = []
    for user in User.objects.all():
        currentProfile = get_object_or_404(Profile, user=user)
        name = (currentProfile.full_name + " Scary Anonymous").strip().split()
        first_name = name[0].title()
        second_name = name[1].title()
        leaderboard.append((currentProfile.score, first_name, second_name, user.username))
    leaderboard = sorted(leaderboard, reverse=True)
    if(len(leaderboard) > 10): leaderboard = leaderboard[:10]
    context["leaderboard"] = leaderboard
    return render(request, "game.html", context)

def profile(request, username):

    if(request.method == "POST"):
        if(request.user.is_authenticated and username == request.user.username):
            form = ProfileForm(request.POST, instance=get_object_or_404(Profile, user=request.user))
            if(form.is_valid()):
                form.save()

        return redirect('story_9:profile', username=username)

    context = copy.copy(original)
    context["description"] = f"{username}'s Profile"
    context["title"] = f"{username}'s Profile"
    context["other_user"] = get_object_or_404(User, username=username)
    context["other_profile"] = get_object_or_404(Profile, user=context["other_user"])
    if(request.user.is_authenticated and username == request.user.username):
        context["form"] = ProfileForm(instance = context["other_profile"])

    return render(request, "profile.html", context)

def loginview(request):
    if(request.method != "GET"):
        return HttpResponseBadRequest("You may not do that!")

    if(request.user.is_authenticated):
        return redirect('story_9:index')

    context = copy.copy(original)
    context["description"] = f"Loggy loggy log log log in"
    context["title"] = f"Your Ordinary Log In Page"
    
    context["form"] = AuthenticationForm()
    return render(request, "login.html", context)

def loginapi(request):
    if(request.is_ajax and request.method == "POST"):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        # print(user)
        # print(type(user))
        if user is not None:
            login(request, user)
            return JsonResponse({"status":200, "message":"Successful"})
        else:
            try:
                user = User.objects.get(username=username)
                return JsonResponse({"status":400, "message":"You entered the wrong password ☹️"})
            except:
                return JsonResponse({"status":400, "message":"No account with this handle is available 👎"})
    return JsonResponse({"status":400, "message":"Something's wrong 😵"})

def signupview(request):
    if(request.method != "GET"):
        return HttpResponseBadRequest("You may not do that!")

    if(request.user.is_authenticated):
        return redirect('story_9:index')

    context = copy.copy(original)
    context["description"] = f"Signy signy sign sign sign in"
    context["title"] = f"Your Casual Sign In Page"
    
    context["form"] = UserCreationForm()

    # print(context["form"])
    return render(request, "signup.html", context)

# def usernameapi(request, username):
#     if(request.is_ajax and request.method == "GET"):
#         try:
#             user = User.objects.get(username=username)
#             return JsonResponse({"status":True})
#         except:
#             return JsonResponse({"status":False})
            
#     return JsonResponse({"status":400, "message":"Something's wrong 😵"})

def signupapi(request):

    if(request.is_ajax and request.method == "POST"):
        # print(request.POST)
        form = UserCreationForm(request.POST)
        if(form.is_valid()):
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, new_user)
            return JsonResponse({"status":200, "message":"Signup Successful ✔️", "username":form.cleaned_data['username']})
        else:
            # print("Verdict__________________________________")
            form = form.__str__()
            # print(form)
            return JsonResponse({"status":400, "message":"Signup Failed 😵", "htmlform":form})

    return JsonResponse({"status":400, "message":"Something's wrong 😵"})

def claim(request):
    profile = get_object_or_404(Profile, user=request.user)
    profile.score += randint(50, 250)
    profile.save()
    return JsonResponse({'score' : profile.score})

story_9/templates/game.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center"
    style="justify-content: flex-start;">
    {% if user.is_authenticated %}
    <h1 class="top-title">Welcome, <span class="bold-font">{{user.username}}</span>!</h1>
    {% else %}
    <h1 class="top-title">Maybee... You Should <a href="{% url 'story_9:login' %}" class="bold-font inline-link">Log In</a>!</h1>
    {% endif %}
    {% include 'messages.html' %}
    <div class="card d-flex align-items-center justify-content-between dark-text">
        <h1>🎌 Leaderboard 🎌</h1>
        {% for people in leaderboard %}
        ️‍<h2 style="margin: 0; padding: 0;">💵 ${{people.0}} | {{ people.1 }} <a href="{% url 'story_9:profile' username=people.3 %}"class="inline-link-dark" style="margin: 0; padding: 0;"><strong>{{ people.3 }}</strong></a> {{ people.2 }}</h2>
        {% empty %}
        <h2><strong>No registered user ☹️</strong></h2>
        {% endfor %}
    </div>
</section>

{% endblock %}

story_9/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
<style>
    .asteriskField{
        display:none;
    }
</style>
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center"
    style="justify-content: flex-start;">
    <h1 class="top-title">Dive <span class="bold-font">In</span></h1>

    {% include 'messages.html' %}

    <div class="card d-flex align-items-center justify-content-between dark-text">
        <form class = "mb-3">
            {% csrf_token %}
            {{form | crispy}}
            <input class="btn btn-light" id="login-button" type="button" value="Log in">
            <a class="btn btn-primary" id="signup-button" href="{% url 'story_9:signup' %}">Sign Up</a>
        </form>
        <p id="message-container"></p>
    </div>
</section>

{% endblock %}

{% block userscript %}
<script>
    $(document).ready(() => {
        $('#loader').hide();
        function login(username, password){
            $.ajax({
                url:"{% url 'story_9:loginapi' %}",
                type: "post",
                headers: {'X-CSRFToken': '{{ csrf_token }}'}, // for csrf token
                data: {'username':username, 'password':password},
                beforeSend: function() {
                    $("#message-container").html(`It will be ready in a second<img style="width: 50px;" src="{% static 'image/loadAmongUs.gif' %}" alt="Load">`)
                },
                success: function (response) {
                    if(response.status === 200){
                        window.location = "{% url 'story_9:profile' username='here' %}".replace('here', username);
                    }else{
                        $("#message-container").html(response.message)
                    }
                }
            })
        }
        $('#login-button').click(()=>{
            const username = $.trim($('#id_username').val());
            const password = $.trim($('#id_password').val());
            login(username, password);
        })
    });
</script>
{% endblock %}

story_9/templates/logout_django.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center"
    style="justify-content: flex-start;">
    <h1 class="top-title">See You <span class="bold-font">Soon</span>!</h1>
    <p>You will be redirected in <span id="countdown"></span></p>
</section>

{% endblock %}

{% block userscript %}
<script>
setTimeout(function() {
    window.location.href = "{% url 'story_9:index'%}";
}, 5000);
let counter = 5;
$('#countdown').html((counter--).toString());
setInterval(() => {
    if(counter > 0) $('#countdown').html((counter--).toString());
}, 1000);

</script>
{% endblock %}

story_9/templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center"
    style="justify-content: flex-start;">
    
    <h1 class="top-title"><span class="bold-font">{{other_user.username}}</span>'s Profile</h1>
    
    
    <div class="card d-flex align-items-center justify-content-between dark-text">
        <img id="img-preview" class="m-3" src="{{other_profile.photo}}" alt="Preview" style="border-radius: 50%; border-style: solid; height: 150px; width: 150px; object-fit: cover; object-position: 50% 0;">
        <h2><strong>🎌 {{other_profile.full_name}} 🎌</strong></h2>
        <h2><strong>💵 <span id="money">{{other_profile.score}}</span> 💵</strong></h2>
        {% if user.username == other_user.username %}
            <input type="button" class="btn btn-success" id="claim-btn" value="Claim">
        {% endif %}
        {% if user.username == other_user.username %}
        <form class="mt-3" action="{% url 'story_9:profile' username=user.username %}" method="post">
            <h2><strong>️‍🌈 Edit Your Profile ️‍🌈</strong></h2>
            {% csrf_token %}
            {{ form | crispy }}
            <input id="preview-btn" class="btn btn-light" type="button" value="Preview">
            <input class="btn btn-light" type="submit" value="Save">
        </form>
        {% endif %}
    </div>
        
    {% include 'messages.html' %}


    
</section>

{% endblock %}

{% block userscript %}
<script>
    $(document).ready(function() {
    const imagePreview = $("#img-preview")
    const imageField = $("#id_photo")
    const previewButton = $("#preview-btn")
    const oldValue = imagePreview.attr('src')
    previewButton.click(function(){ imagePreview.attr('src', imageField.val()); })
    imagePreview.on("error", function () {
        $(this).attr("src", oldValue)
    });
    $('#claim-btn').click(()=>{
        $.get("{% url 'story_9:claim' %}", (response)=>{
            $("#money").html(response.score)
        })
    })
});
</script>
{% endblock %}

story_9/templates/signup.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
<style>
    .asteriskField{
        display:none;
    }
    .form-text{
        display: none;
    }
</style>
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center"
    style="justify-content: flex-start;">
    <h1 class="top-title">Sign Yourself <span class="bold-font">Up</span></h1>

    {% include 'messages.html' %}

    <div class="card d-flex align-items-center justify-content-between dark-text">
        <form class = "mb-3" id="signup-form">
            {% csrf_token %}
            {{form | crispy}}
            <input class="btn btn-light" id="signup-button" type="button" value="Sign up">
        </form>
        <p id="message-container"></p>
    </div>
</section>

{% endblock %}

{% block userscript %}
<script>
    $(document).ready(() => {
        function signup(form){
            $.ajax({
                url:"{% url 'story_9:signupapi' %}",
                type: "post",
                headers: {'X-CSRFToken': '{{ csrf_token }}'}, // for csrf token
                data: form,
                beforeSend: function() {
                    $("input").removeClass("is-valid")
                    $("input").removeClass("is-invalid")
                    $("input").parent().children(".invalid-feedback").remove()
                    $("#message-container").html(`Sending your data to the government<img style="width: 50px;" src="{% static 'image/loadAmongUs.gif' %}" alt="Load">`)
                },
                success: function (response) {
                    if(response.status === 200){
                        window.location = "{% url 'story_9:profile' username='here' %}".replace('here', response.username);
                    }else{
                        const field = ["username", "password1", "password2"]
                        response.htmlform = $.parseHTML(response.htmlform);
                        $.each(field, function(fieldidx, fieldval){
                            const current = $(`[name='${fieldval}']`).parent();
                            const formupd = $(response.htmlform).find(`[name='${fieldval}']`).parent();
                            const errorlist = $(formupd).find(".errorlist > li")
                            if(errorlist.length === 0){
                                $(current).children("input").addClass("is-valid")
                            }else{
                                $(current).children("input").addClass("is-invalid")
                                $.each(errorlist,function(erroridx, errorval){
                                    // console.log()
                                    $(current).children("input").after(`<p class="invalid-feedback"><strong>${$(this).text()}</strong></p>`);
                                })
                            }
                        })
                        $("#message-container").html(response.message)
                    }
                }
            })
        }
        $('#signup-button').click(()=>{
            signup($('#signup-form').serialize());
        })
    });
</script>
{% endblock %}