story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('story-1/', include('story_1.urls')),

    # path('story-x/', include('story_x.urls')), do this for each new story, and update the landing page with the latest story

    path('error/', include('error_handler.urls')),
    path('profile/', include('story_1.urls')),
    path('', include('story_3.urls')),
    path('schedule/', include('story_5.urls')),
    path('activity/', include('story_6.urls')),
    path('flexes/', include('story_7.urls')),
    path('books/', include('story_8.urls')),
    path('game/', include('story_9.urls')),
    path('copypasta/', include('copypasta.urls')),
]

handler400 = 'error_handler.views.error_400'
handler403 = 'error_handler.views.error_403'
handler404 = 'error_handler.views.error_404'
handler500 = 'error_handler.views.error_500'

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    # views.<method in views> here
    path('', views.index, name='activity'),
    path('add/', views.add_activity, name='add_activity'),
    path('delete/<int:id>/', views.delete_activity, name='delete_activity'),
    path('delete-person/<int:id>/', views.delete_person, name='delete_person')
]

story_6/models.py
from django.db import models

class Activity(models.Model):
    name = models.CharField(max_length = 50, default = "Fun activity")
    category = models.CharField(max_length = 20, choices=[(x, x) for x in ["🎮 Game", "🎨 Art", "📢 Talk"]], default = "🎮 Game")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Activities"


class Person(models.Model):
    name = models.CharField(max_length = 50)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "People"

story_6/forms.py
from django.forms import ModelForm
from .models import Person, Activity
from crispy_forms.helper import FormHelper

class ActivityForm(ModelForm):
    class Meta():
        model = Activity
        fields = '__all__'

class PersonForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['name'].label = ''

    class Meta():
        model = Person
        fields = '__all__'

story_6/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Activity, Person
from .forms import ActivityForm, PersonForm
from django.contrib import messages
import copy

original = {
    "description" : "Hocky Yudhiono's personal website",
    "title" : "Hey! It's Hocky!",
    "showfooter" : True,
    "stickynav" : True,
    "ismain" : False,
}

def index(request):
    context = copy.copy(original)
    context["description"] = "List of activities"
    context["title"] = "Fun! Fun! Activities!"
    context["activities"] = Activity.objects.all()
    form = PersonForm(request.POST or None)
    if(form.is_valid()):
        name = form.cleaned_data['name']
        messages.success(request, f'Successfully added {name}')
        form.save()
        return redirect('story_6:activity')

    context["form"] = form
    return render(request, "activity.html", context)

def add_activity(request):
    context = copy.copy(original)
    context["description"] = "Add more activities here!"
    context["title"] = "Fun! Fun! Activities!"

    form = ActivityForm(request.POST or None)
    if(form.is_valid()):
        name = form.cleaned_data['name']
        messages.success(request, f'Successfully added {name} activity')
        form.save()
        return redirect('story_6:activity')

    context["form"] = form
    return render(request, "add_activity.html", context)


def delete_activity(request, id):
    activity = get_object_or_404(Activity, id=id)

    messages.success(request, f'Successfullydeleted {activity}')
    activity.delete()

    return redirect('story_6:activity')

def delete_person(request, id):
    person = get_object_or_404(Person, id=id)

    messages.success(request, f'Successfully deleted {person}')
    person.delete()

    return redirect('story_6:activity')

story_6/templates/activity.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'style/empty-label-form.css' %}" type="text/css">
{% endblock %}


{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center">
    <h1 class="top-title">Daily <span class="bold-font">Activities</span></h1>

    {% include 'messages.html' %}

    <a class="link-card card d-flex align-items-center justify-content-center" href="{% url 'story_6:add_activity' %}">
        <h2 class="dark-text">
            Add activity <i class="fas fa-plus"></i>
        </h2>
    </a>

    <div class="my-container p-3 mr-4 mb-5{% if activities %} card-columns{% endif %}">

        {% for activity in activities reversed %}
        <li class="card inlinedis d-flex align-items-center dark-text">
            <div class="d-flex flex-row justify-content-center align-items-center">
                <h2 class="m-0"> <b>{{ activity.name }}</b> </h2>
                <form class="m-2" action="{% url 'story_6:delete_activity' id=activity.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                </form>
            </div>

            <p>{{ activity.category }}</p>

            {% if activity.person_set.all %}
            <h3><b>Daftar Peserta:</b></h3>
            {% endif %}
            {% for person in activity.person_set.all %}
            <div class="m-2">
                <h3 style="display: inline;"> {{ person.name }} </h3>
                <form style="display: inline;" action="{% url 'story_6:delete_person' id=person.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">❌</button>
                </form>
            </div>
            {% empty %}
            <h3>Tidak ada peserta! ❌</h3>
            {% endfor %}

            <form action="{% url 'story_6:activity'%}" method="post">
                {% csrf_token %}
                <input type="hidden" name="activity" value="{{ activity.id }}">
                <div class="d-flex flex-row align-items-center justify-content-center m-1">
                    {{form.name|as_crispy_field}}
                    <button class="btn btn-success ml-3" type="submit"><i class="fas fa-plus"></i></button>
                </div>
            </form>


        </li>
        {% empty %}
        <h1 class="m">
            No available activities! <i class="far fa-sad-tear"></i>
        </h1>
        {% endfor %}
    </div>
</section>

{% endblock %}

{% block userscript %}
{% endblock %}

story_6/templates/add_activity.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"
    integrity="sha512-F636MAkMAhtTplahL9F6KmTfxTmYcAcjcCkyu0f0voT3N/6vzAuJ4Num55a0gEJ+hRLHhdz3vDvZpf6kqgEa5w=="
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css"
    integrity="sha512-hievggED+/IcfxhYRSr4Auo1jbiOczpqpLZwfTVL/6hFACdbI3WQ8S9NCX50gsM9QVE+zLk/8wb9TlgriFbX+Q=="
    crossorigin="anonymous" />
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'style/formstyle.css' %}" type="text/css">
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center">
    <h1 class="top-title">Add <span class="bold-font">Activity</span></h1>

    {% include 'messages.html' %}

    <div class="card d-flex align-items-center justify-content-between dark-text">
        <form action="{% url 'story_6:add_activity' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Add activity <i class="fas fa-plus"></i></button>
            <a href="{% url 'story_6:activity' %}" class="btn btn-dark">Back <i class="far fa-hand-point-left"></i></a>
        </form>
    </div>
</section>

{% endblock %}

{% block userscript %}
{% endblock %}