story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('story-1/', include('story_1.urls')),

    # path('story-x/', include('story_x.urls')), do this for each new story, and update the landing page with the latest story

    path('error/', include('error_handler.urls')),
    path('profile/', include('story_1.urls')),
    path('', include('story_3.urls')),
    path('schedule/', include('story_5.urls')),
    path('activity/', include('story_6.urls')),
    path('flexes/', include('story_7.urls')),
    path('books/', include('story_8.urls')),
    path('game/', include('story_9.urls')),
    path('copypasta/', include('copypasta.urls')),
]

handler400 = 'error_handler.views.error_400'
handler403 = 'error_handler.views.error_403'
handler404 = 'error_handler.views.error_404'
handler500 = 'error_handler.views.error_500'

story_1/urls.py
from django.urls import path
from . import views

app_name = 'story_1'

urlpatterns = [
    # views.<method in views> here
    path('', views.index, name='profile'),
]

story_3/urls.py
from django.urls import path
from . import views

app_name = 'story_3'

urlpatterns = [
    # views.<method in views> here
    path('', views.index, name='home'),
    path('gallery/', views.gallery, name='gallery'),
]

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'

urlpatterns = [
    # views.<method in views> here
    path('', views.schedule, name='schedule'),
    path('add/', views.add_course, name='add_course'),
    path('delete/<int:id>/', views.delete_course, name='delete_course'),
    path('deleteasg/<int:id>/', views.delete_assignment, name='delete_assignment'),
    path('detail/<int:id>/', views.detail_course, name='detail_course')
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    # views.<method in views> here
    path('', views.index, name='activity'),
    path('add/', views.add_activity, name='add_activity'),
    path('delete/<int:id>/', views.delete_activity, name='delete_activity'),
    path('delete-person/<int:id>/', views.delete_person, name='delete_person')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'image/favicon.ico' type='image/x-icon' %}">
  <meta charset="utf-8" />
  <meta name="keywords" content="Personal Web, About Me" />
  <meta name="author" content="Hocky Yudhiono" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <meta name="description" content="{{ description }}" />
  <title>{{ title }}</title>

  <!-- jQuery -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
    crossorigin="anonymous"></script>

  <!-- Bootstrap op framework orz -->
  <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}"/>

  <script src="{% static 'script/bootstrap.min.js' %}"></script>

  <!-- Font Awesome why so good orz -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
    crossorigin="anonymous" />

  <!-- Montserrat font -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet" />

  {% block cdnscript %} {% endblock %}

  <!-- Parallax orz -->
  <link href="{% static 'style/style.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'style/nav.css' %}" rel="stylesheet" type="text/css" />
  {% block style %} {% endblock %}

</head>

<body>

  {% block intro %} {% endblock %}

  {% include "nav.html" %}

  {% block content %} {% endblock %}
  {% if showfooter %}
    {% include "footer.html" %}
  {% endif %}
</body>

<script src="{% static 'script/scroll.js' %}"></script>

{% block userscript %} {% endblock %}

</html>

templates/footer.html
{% load static %}

<footer id="contact-me" class="footer-container d-flex flex-column light-color align-items-center">
  <div id="social">
    <p>
      <a href="https://www.facebook.com/HockyYudhiono"><i id="social-fb" class="fab fa-facebook fa-3x social"></i></a>
      <a href="mailto:hocky.yudhiono@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
      <a href="https://github.com/hockyy"><i id="social-git" class="fab fa-github fa-3x social"></i></a>
      <a href="https://api.whatsapp.com/send?phone=+6281807240802"><i id="social-wa"
          class="fab fa-whatsapp-square fa-3x social"></i></a>
      <a href="https://www.linkedin.com/in/hocky/"><i id="social-li" class="fab fa-linkedin fa-3x social"></i></a>
      <a href="https://www.instagram.com/__hocky/"><i id="social-ig"
          class="fab fa-instagram-square fa-3x social"></i></a>
    </p>
  </div>
  <div id="fb-message">
    <strong>Facebook</strong> is pretty cool to chat!
  </div>
  <div id="em-message">
    <strong>Email</strong> for legit and serious stuffs I guess(?)
  </div>

  <div id="git-message">
    Check my <strong>Github</strong> here!
  </div>

  <div id="wa-message">
    <strong>Whatsapp</strong> can bring us pretty close..
  </div>
  <div id="li-message">
    <strong>LinkedIn</strong> is like portfolio on steroid.
  </div>
  <div id="ig-message">
    Check my daily life on <strong>Instagram</strong>
  </div>
</footer>

<script src="{% static 'script/social.js' %}"></script>

templates/messages.html
{% if messages %}
    <ul class="messages container mt-4 mb-0" style="list-style: none;">
        {% for message in messages %}
        {% if message.tags == "error" %} <li  class="alert alert-danger alert-dismissible fade show" >
        {% else %} <li  class="alert alert-{{ message.tags }} alert-dismissible fade show" >{% endif %}
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
        {% endfor %}
    </ul>
{% endif %}

templates/nav.html
<nav id="main-navbar" class="navbar navbar-expand-lg sticky-top {%if stickynav %}sticky{%endif%}"
  style="background-color: #2D112B">

  <a class=" navbar-brand nav-link" href="{% url 'story_3:home' %}">💜 Hocky's Cluckies</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
      class="navbar-toggler-icon">
      <i class="fas fa-bars" style="color:#fff; font-size:28px;"></i>
    </span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="nav navbar-nav ml-auto navbar-right">
      {% if not ismain %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_3:home' %}"><strong>Home</strong></a>
      </li>
      {% endif %}
      {% if ismain %}
      <li class="nav-item">
        <a class="nav-link" href="#intro"><strong>Home</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#contact-me">Contact</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_5:schedule' %}"><strong>Schedule</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_6:activity' %}"><strong>Activity</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_7:accordion' %}"><strong>Flexes</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_8:books' %}"><strong>Books</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_1:profile' %}"><strong>Biodata</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_3:gallery' %}"><strong>Gallery</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_9:index' %}"><strong>Game</strong></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_9:profile' username=user.username %}"><strong>Profile</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_9:logout' %}"><strong>Log Out</strong></a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story_9:login' %}"><strong>Log In</strong></a>
      </li>
      {% endif %}
    </ul>


  </div>

</nav>