story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('story-1/', include('story_1.urls')),

    # path('story-x/', include('story_x.urls')), do this for each new story, and update the landing page with the latest story

    path('error/', include('error_handler.urls')),
    path('profile/', include('story_1.urls')),
    path('', include('story_3.urls')),
    path('schedule/', include('story_5.urls')),
    path('activity/', include('story_6.urls')),
    path('flexes/', include('story_7.urls')),
    path('books/', include('story_8.urls')),
    path('game/', include('story_9.urls')),
    path('copypasta/', include('copypasta.urls')),
]

handler400 = 'error_handler.views.error_400'
handler403 = 'error_handler.views.error_403'
handler404 = 'error_handler.views.error_404'
handler500 = 'error_handler.views.error_500'

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'

urlpatterns = [
    # views.<method in views> here
    path('', views.schedule, name='schedule'),
    path('add/', views.add_course, name='add_course'),
    path('delete/<int:id>/', views.delete_course, name='delete_course'),
    path('deleteasg/<int:id>/', views.delete_assignment, name='delete_assignment'),
    path('detail/<int:id>/', views.detail_course, name='detail_course')
]

story_5/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
import datetime

def get_year_choice():
    return [(year, f'{year}/{year+1}') for year in range(datetime.date.today().year-2, datetime.date.today().year+2)];

def get_parity():
    return datetime.date.today().month > 6

class Instructor(models.Model):
    name = models.CharField(max_length=100)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    gender = models.BooleanField(default=True)
    email = models.EmailField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["rating"]

class Course(models.Model):
    name = models.CharField(max_length=50)
    instructors = models.ManyToManyField(Instructor)
    credit = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(20)], default=3)
    description = models.TextField(default="A fun programming course any beginners can have!")
    semester_parity = models.BooleanField(default=get_parity())
    semester_year = models.IntegerField(choices=get_year_choice(), default=datetime.date.today().year)
    room = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name} - {self.semester_year}/{self.semester_year+1} {"Gasal" if self.semester_parity else "Genap"} - {self.credit} credit(s)'

class Assignment(models.Model):
    name = models.CharField(max_length=30)
    deadline = models.DateTimeField()
    course = models.ForeignKey(Course, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["deadline"]

story_5/forms.py
from django.forms import ModelForm, DateTimeInput, CheckboxInput
from .models import *


class InstructorForm(ModelForm):
    class Meta:
        model = Instructor
        fields = '__all__'


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        labels = {
            'name': 'Course Name',
            'semester_parity': 'Semester',
            'semester_year': 'Year'
        }
        widgets = {
            'semester_parity': CheckboxInput(attrs={'data-toggle': 'toggle', 'data-on': "Odd", "data-off": "Even", 'data-onstyle':'primary', 'data-offstyle':'warning'})
        }

class AssignmentForm(ModelForm):

    class Meta:
        model = Assignment
        fields = '__all__'
        labels = {
            'name': 'Assignment Name'
        }
        widgets = {
            'deadline': DateTimeInput(attrs={'class': 'datetimepicker'}),
        }

story_5/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Course, Assignment
from .forms import CourseForm, AssignmentForm
from django.contrib import messages
import copy

original = {
    "description" : "Hocky Yudhiono's personal website",
    "title" : "Hey! It's Hocky!",
    "showfooter" : True,
    "stickynav" : True,
    "ismain" : False,
}

def schedule(request):
    context = copy.copy(original)
    context["description"] = "Add your daily schedule here!"
    context["title"] = "Coursey Coursey"
    context["courses"] = Course.objects.all()
    return render(request, "schedule.html", context)


def add_course(request):
    context = copy.copy(original)
    context["description"] = "Add your daily schedule here!"
    context["title"] = "Coursey Coursey"

    form = CourseForm(request.POST or None)
    if(form.is_valid()):
        # print(request.POST)
        course_name = form.cleaned_data['name']
        messages.success(request, f'Successfully added {course_name} Course')
        form.save()
        return redirect('story_5:schedule')

    context["form"] = form
    return render(request, "add_course.html", context)

    
def delete_course(request, id):

    context = copy.copy(original)
    context["course"] = get_object_or_404(Course,id=id)
    if request.method == 'POST':
        messages.success(request, f'Successfully deleted {context["course"].name} Course')
        context["course"].delete()
        return redirect('story_5:schedule')

    context["title"] = f'Delete {context["course"].name}'
    context["description"] = f'Delete {context["course"].name}'
    context["toptitle1"] = "Are you sure you want to delete"
    context["toptitle2"] = f'{context["course"].name}?'
    context["show_delete"] = True
    return render(request, "detail_course.html", context)

def delete_assignment(request, id):

    assignment = get_object_or_404(Assignment, id=id)
    if request.method == 'POST':
        messages.success(request, f'Successfully deleted {assignment} assignment')
        assignment.delete()

    course = request.POST.get('course')
    return redirect('story_5:detail_course', id=course)
    
def detail_course(request, id):
    context = copy.copy(original)
    context["course"] = get_object_or_404(Course,id=id)
    context["title"] = f'{context["course"].name}'
    context["description"] = f'{context["course"].name} course detail'
    context["toptitle1"] = "Course"
    context["toptitle2"] = "Detail"
    context["assignments"] = Assignment.objects.filter(course=context["course"])

    form = AssignmentForm(request.POST or None)

    if(form.is_valid()):
        assignment_name = form.cleaned_data['name']
        messages.success(request, f'Successfully added {assignment_name} Assignment')
        form.save()
        form = AssignmentForm()

    context["form"] = form

    return render(request, "detail_course.html", context)

story_5/templates/add_course.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"
    integrity="sha512-F636MAkMAhtTplahL9F6KmTfxTmYcAcjcCkyu0f0voT3N/6vzAuJ4Num55a0gEJ+hRLHhdz3vDvZpf6kqgEa5w=="
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css"
    integrity="sha512-hievggED+/IcfxhYRSr4Auo1jbiOczpqpLZwfTVL/6hFACdbI3WQ8S9NCX50gsM9QVE+zLk/8wb9TlgriFbX+Q=="
    crossorigin="anonymous" />
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'style/formstyle.css' %}" type="text/css">
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center">
    <h1 class="top-title">Add <span class="bold-font">Course</span></h1>

    {% include 'messages.html' %}

    <div class="card d-flex align-items-center justify-content-between dark-text">
        <form action="{% url 'story_5:add_course' %}" method="post">
            {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.credit|as_crispy_field }}
                </div>
            </div>
            {{ form.description|as_crispy_field }}
            {{ form.instructors|as_crispy_field }}
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ form.semester_year|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.semester_parity|as_crispy_field }}
                </div>
            </div>
            {{ form.room|as_crispy_field }}
            <!-- {{ form|crispy }} -->
            <button class="btn btn-success" type="submit">Add course <i class="fas fa-plus"></i></button>
            <a href="{% url 'story_5:schedule' %}" class="btn btn-dark">Back <i class="far fa-hand-point-left"></i></a>
        </form>
    </div>
</section>

{% endblock %}

{% block userscript %}
{% endblock %}

story_5/templates/detail_course.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
    integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw=="
    crossorigin="anonymous"></script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
    integrity="sha512-f0tzWhCwVFS3WeYaofoLWkTP62ObhewQ1EZn65oSYDZUg1+CyywGKkWzm8BxaJj5HGKI72PnMH9jYyIFz+GH7g=="
    crossorigin="anonymous" />
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
{% endblock %}

{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center">

    <h1 class="top-title">{{toptitle1}} <span class="bold-font">{{toptitle2}}</span></h1>

    {% include 'messages.html' %}

    <div class="card d-flex align-items-center justify-content-between dark-text">
        <h2 class="dark-text"><b>{{ course.name }}</b> - {{course.credit}} credit{% if course.credit > 1 %}s{% endif %}
        </h2>
        <p class="m-1">
            <b>{{course.semester_year}}/{{course.semester_year|add:'1'}}
                {% if course.semester_parity %} Odd {% else %} Even {% endif %} Semester</b> <br>
            {{course.description}} </p>
        <hr class="dark-hr" />
        <p>
            <b>Instructors</b> <br>
            {% for instructor in course.instructors.all %}
            {{instructor.name}} <br>
            {% empty %}
            No instructors found in this class!
            {% endfor %}
        </p>
        <p>
            <b>Classroom</b> <br>
            {{course.room}}
        </p>
        <div class="card-action">
            <div class="float-right">
                {% if show_delete %}
                <form method="POST"> {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Delete Course <i class="fa fa-trash"></i></button>
                    <a href="{% url 'story_5:schedule' %}" class="btn btn-dark">Hol' Up <i
                            class="far fa-hand-point-left"></i></a>
                </form>
                {% else %}
                <a href="{% url 'story_5:schedule' %}" class="btn btn-dark">Back <i
                        class="far fa-hand-point-left"></i></a>
                {% endif %}
            </div>
        </div>
    </div>

    {% if not show_delete %}
    <div class="card d-flex align-items-center justify-content-between dark-text">
        <h2 class="dark-text"><b>Oh Assignments! <i class='far fa-dizzy'></i></b></h2>
        <hr class="dark-hr" />
        <div class="card-action">
            <div class="float-right">
                <form action="{% url 'story_5:detail_course' id=course.id %}" method="post">
                    {% csrf_token %}
                    {{ form.name|as_crispy_field }}
                    {{ form.deadline|as_crispy_field }}
                    <input type="hidden" name="course" value="{{ course.id }}">
                    <button class="btn btn-success" type="submit">Add assignment <i class="fas fa-plus"></i></button>
                </form>
            </div>
        </div>
    </div>

    {% for assignment in assignments %}

    <div class="card d-flex align-items-center justify-content-between dark-text">
        <h2 class="dark-text"><b>{{ assignment.name }}</b></h2>
        <p class="m-1">
            <b>{{assignment.deadline}}</b> <br>
        </p>
        <hr class="dark-hr" />
        <p>{{assignment.description}} </p>
        <div class="card-action">
            <div class="float-right">
                <form action="{% url 'story_5:delete_assignment' id=assignment.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="course" value="{{ course.id }}">
                    <button type="submit" class="btn btn-success">This task is done! <i class="fas fa-check"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</section>

{% endblock %}

{% block userscript %}
<script type="text/javascript">
    $(function () {
        $(".datetimepicker").datetimepicker({
            format: 'Y-m-d H:i:s',
        });
    });
</script>
{% endblock %}

story_5/templates/schedule.html
{% extends 'base.html' %}

{% load static %}

{% block cdnscript %}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'style/note-card.css' %}" type="text/css">
{% endblock %}


{% block content %}
<section id="first-section" class="my-container d-flex flex-column dark-color align-items-center text-center">
    <h1 class="top-title">Daily <span class="bold-font">Schedule</span></h1>

    {% include 'messages.html' %}

    <a class="link-card card d-flex align-items-center justify-content-center" href="{% url 'story_5:add_course' %}">
        <h2 class="dark-text">
            Add a course <i class="fas fa-plus"></i>
        </h2>
    </a>

    <div class="my-container p-3 mr-4 mb-5{% if courses %} card-columns{% endif %}">

        {% for course in courses reversed %}
        <li class="card inlinedis d-flex align-items-center">
            <a class="link-unstyled" href="{% url 'story_5:detail_course' id=course.id %}">
                <h2> <b>{{ course.name }}</b> </h2>
            </a>

            <p class="dark-text">{{course.description}}</p>
            <div class="btnwrapper">
                <a href="{% url 'story_5:detail_course' id=course.id %}" class="btn btn-dark">More</a>
                <a href="{% url 'story_5:delete_course' id=course.id %}" class="btn btn-danger"><i
                        class="fa fa-trash"></i></a>
            </div>
        </li>
        {% empty %}
        <h1 class="m-5">
            No available courses! <i class="far fa-sad-tear"></i>
        </h1>
        {% endfor %}
    </div>
</section>

{% endblock %}

{% block userscript %}
{% endblock %}